export const GET_MUSIC_LIBRARY = 'GET_MUSIC_LIBRARY';
export const GET_MUSIC_LIBRARY_FUFILLED = 'GET_MUSIC_LIBRARY_FUFILLED';
export const GET_BEARER_TOKEN = 'GET_BEARER_TOKEN';
export const GET_BEARER_TOKEN_FUFILLED = 'GET_BEARER_TOKEN_FUFILLED';
